<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <OutputType>WinExe</OutputType>
  </PropertyGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <!--    <RuntimeIdentifiers>win-x64;linux-x64;linux-arm64;osx-x64;osx-arm64</RuntimeIdentifiers>-->
    <Nullable>enable</Nullable>
    <TrimMode>full</TrimMode>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <RootNamespace>UlReg</RootNamespace>
    <IsPackable>False</IsPackable>
  </PropertyGroup>

  <PropertyGroup>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)'=='Release'">
    <PublishAot>True</PublishAot>
    <TrimmerSingleWarn>false</TrimmerSingleWarn>
    <DebugSymbols>False</DebugSymbols>
    <DebugType>None</DebugType>
    <TrimmerRemoveSymbols>true</TrimmerRemoveSymbols>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.Desktop" Version="$(AvaloniaVersion)"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\UlReg.Ui\UlReg.Ui.csproj" />
  </ItemGroup>

  <Target BeforeTargets="Publish" Name="asdf">
    <Message Text="oop there we go aagi= $(MSBuildProjectFile)" Importance="high" />
    <Message Text="$(AssemblyName)" Importance="high" />
    <Message Text="$(RootNamespace)" Importance="high" />
    <Message Text="$(PublishDir)" Importance="high" />
  </Target>

  <PropertyGroup>
    <MacosBundleName>Universal Labels.app</MacosBundleName>
  </PropertyGroup>


  <Target DependsOnTargets="PublishItemsOutputGroup" AfterTargets="PublishItemsOutputGroup" Name="asdf">
    <ItemGroup>
      <LibsAndExe Include="$(PublishDir)*.dylib;$(PublishDir)$(AssemblyName)" />
    </ItemGroup>
    <Message Text="oop there we go aagi= $(MSBuildProjectFile)" Importance="high" />
    <Message Text="$(AssemblyName)" Importance="high" />
    <Message Text="$(RootNamespace)" Importance="high" />
    <Message Text="publish dir: $(PublishDir)" Importance="high" />
    <RemoveDir Directories="$(ArtifactsPath)/$(MacosBundleName)" />
<!--    <MakeDir Directories="$(ArtifactsPath)/$(MacosBundleName)/Contents/MacOS"/>-->
<!--    <MakeDir Directories="$(ArtifactsPath)/$(MacosBundleName)/Contents/Resources"/>-->
    <Message Text="copying plist" Importance="high" />
    <Copy SourceFiles="$(ProjectDir)/Info.plist" DestinationFolder="$(ArtifactsPath)/$(MacosBundleName)/Contents"/>
    <Message Text="copying icons" Importance="high" />
    <Copy SourceFiles="$(ProjectDir)/icon.icns" DestinationFolder="$(ArtifactsPath)/$(MacosBundleName)/Contents/Resources"/>
    <Message Text="copying dylib and exe: @(LibsAndExe)" Importance="high" />
    <Message Text="                   to: $(ArtifactsPath)/$(MacosBundleName)/Contents/MacOS" Importance="high" />
    <Copy UseHardlinksIfPossible="true" SourceFiles="@(LibsAndExe)" DestinationFolder="$(ArtifactsPath)/$(MacosBundleName)/Contents/MacOS"/>
    <Message Text="now tree" Importance="high" />
    <Hash ItemsToHash="@(LibsAndExe)" HashResult="LibsAndExeHashes" />
    <Message Text="@(LibsAndExeHashes)" Importance="high" />
    <Exec Command="tree --du -h '$(ArtifactsPath)/$(MacosBundleName)/'" >
      <Output TaskParameter="ConsoleOutput" PropertyName="dunno" />
    </Exec>
  </Target>


</Project>
